---

# When installing extra repositories (such as test-updates), these
# repositories are served to cloud nodes using the FQDN instead of the IP,
# which confuses crowbar_register
- name: Ensure admin node FQDN resolvable
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ hostvars['localhost'].admin_conf_ip }}    crowbar.{{ cloud_fqdn }}"

- name: Remove existing repositories (except Maint. Updates)
  shell: |
    set -e
    for repo in $(zypper lr | grep -v "Maint-Update-" | awk '/Yes/ { print $3 }'); do
      zypper rr $repo
    done

- name: Run crowbar_register
  shell: |
    set -e

    wget {{ crowbar_register_url }} -O {{ crowbar_register_path }}
    chmod +x {{ crowbar_register_path }}

    SSH_CONNECTION= {{ crowbar_register_path }} -f --interface {{ admin_interface }} --gpg-auto-import-keys 2>&1 | tee {{ crowbar_register_log }}
    exit ${PIPESTATUS[0]}

- name: Check that node has registered
  delegate_to: "{{ cloud_env }}"
  shell: knife node list | tr -d ' '
  register: _register_tmp
  # The more nodes we have, the longer this will take
  retries: "{{ 6 * ( groups['cloud_virt_hosts'] | length ) }}"
  until: _register_tmp.rc == 0 and crowbar_node_name in _register_tmp.stdout_lines
  delay: 10
